export interface Account { id:string; name:string; balance:number; type:'deposit'|'credit'|'loan'|'external' }
export interface Transaction { id:string; name:string; amount:number; date:string }
export interface Member { id:string; firstName:string; description:string; accounts:Account[]; transactions:Transaction[] }
export const members:Member[]=[
{id:'molly',firstName:'Molly',description:'A new relationship. Room to grow.',accounts:[{id:'4821',name:'Everyday Checking',balance:3240.50,type:'deposit'},{id:'9302',name:'Member Savings',balance:5180,type:'deposit'},{id:'6014',name:'Visa Credit Card',balance:342.18,type:'credit'}],transactions:[{id:'1',name:'Market Street Coffee',amount:-6.50,date:'Today'},{id:'2',name:'Payroll deposit',amount:2450,date:'Yesterday'},{id:'3',name:'Neighborhood Market',amount:-54.82,date:'Sep 28'}]},
{id:'shane',firstName:'Shane',description:'Everyday life. Bigger milestones.',accounts:[{id:'7042',name:'Everyday Checking',balance:6840.25,type:'deposit'},{id:'1944',name:'Member Savings',balance:18400,type:'deposit'},{id:'8091',name:'Home Mortgage',balance:248650,type:'loan'},{id:'3701',name:'Auto Loan',balance:12480,type:'loan'}],transactions:[{id:'1',name:'Home loan payment',amount:-1840,date:'Today'},{id:'2',name:'Payroll deposit',amount:3820,date:'Yesterday'},{id:'3',name:'City Utilities',amount:-124.50,date:'Sep 28'}]},
{id:'albert',firstName:'Albert',description:'Personal ambitions. Business possibilities.',accounts:[{id:'5028',name:'Everyday Checking',balance:4120.80,type:'deposit'},{id:'9301',name:'Member Savings',balance:26300,type:'deposit'},{id:'1153',name:'Business Checking',balance:12850,type:'deposit'},{id:'6610',name:'External Account',balance:7500,type:'external'}],transactions:[{id:'1',name:'Client payment',amount:4200,date:'Today'},{id:'2',name:'Office supplies',amount:-86.40,date:'Yesterday'},{id:'3',name:'Neighborhood Market',amount:-42.10,date:'Sep 28'}]}
];
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export interface Capability {id:string;experience:string;component:string;service:string;endpoint:string|null;description:string}
export const capabilityMap:Capability[]=[
['accounts','Available balance','AccountSummary','Accounts API','A clear view of where money lives.'],['transactions','Recent transactions','TransactionList','Transactions API','A consistent view of account activity.'],['transfers','Move money','MoneyMovement','Transfers API','One entry point for money movement.'],['cards','Card controls','CardManagement','Cards API','Manage the cards used every day.'],['documents','Statements & documents','DocumentCenter','Documents API','Important records in one familiar place.'],['profile','Member profile','MemberProfile','Profile API','Member details within a shared framework.'],['insights','Financial insights','InsightsPanel','Insights capability','Useful context for financial decisions.'],['authentication','Secure access','Authentication','Authentication capability','Access to the member relationship.'],['notifications','Notifications','NotificationCenter','Notifications capability','Updates members can understand.'],['member-data','Member data','MemberContext','Member Data capability','Personalized content, consistent behavior.']
].map(([id,experience,component,service,description])=>({id,experience,component,service,description,endpoint:null}));
export const journey=[{title:'Join BECU',detail:'A welcoming start to the relationship.',screen:'Your next chapter starts here.',action:'Explore membership',icon:'01'},{title:'Establish membership',detail:'Build a secure member identity.',screen:'A place to belong.',action:'Membership established',icon:'02'},{title:'Open an account',detail:'Choose an account for everyday life.',screen:'Make room for everyday.',action:'Everyday Checking selected',icon:'03'},{title:'Fund the account',detail:'Bring money into the same connected flow.',screen:'A strong first step.',action:'Illustrative opening deposit: $250',icon:'04'},{title:'Start banking',detail:'Arrive in a familiar, authenticated experience.',screen:'Welcome home, Molly.',action:'Your accounts, together',icon:'05'}];
