"use client";
import BecuLogo from '@/components/becu-logo';
import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,Home,ArrowLeftRight,CreditCard,List,ChevronRight,Check,ArrowLeft} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {members,money,type Member,journey} from '@/lib/experience-data';
export function BankingApp({member=members[0],route='/home',mode='interactive',onCapability}:{member?:Member;route?:string;mode?:'interactive'|'display';onCapability?:(id:string)=>void}){
 const [view,setView]=useState(route);const [account,setAccount]=useState<string|null>(null);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{setView(route)},[route]);useEffect(()=>{setAccount(null);if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)ref.current?.animate([{opacity:.45,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:320})},[member.id]);
 const go=(path:string)=>{setView(path);setAccount(null);onCapability?.(path==='/activity'?'transactions':path==='/move'?'transfers':path==='/cards'?'cards':'accounts')};
 return <div className="phone"><div className="island"/><div className="phone-top">9:41 <span>••• ▰</span></div><div className="app-brand"><BecuLogo/> <span>◈</span></div><div className="phone-content" ref={ref}>
 {view==='/home'?<><div className="greeting">Good morning, {member.firstName}.</div><h3>A little clarity.<br/>A lot of possibility.</h3><button className="balance" onClick={()=>{go('/accounts');onCapability?.('accounts')}} disabled={mode==='display'}><small>TOTAL DEPOSIT BALANCE</small><strong>{money(member.accounts.filter(a=>a.type==='deposit').reduce((s,a)=>s+a.balance,0))}</strong><span>Across your BECU deposit accounts</span></button><div className="quick-actions"><button disabled={mode==='display'} onClick={()=>go('/move')}><ArrowUpRight/><small>Move money</small></button><button disabled={mode==='display'} onClick={()=>go('/activity')}><List/><small>Activity</small></button><button disabled={mode==='display'} onClick={()=>go('/cards')}><CreditCard/><small>Cards</small></button></div></>:<h3 className="view-title">{view==='/accounts'?'Your accounts':view==='/activity'?'Recent activity':view==='/cards'?'Your cards':'Move money'}</h3>}
 {(view==='/home'||view==='/accounts')&&<><h4>Your accounts <button disabled={mode==='display'} onClick={()=>go('/accounts')}>View all →</button></h4>{member.accounts.slice(0,view==='/home'?2:undefined).map(a=><button disabled={mode==='display'} className="account" key={a.id} onClick={()=>{setAccount(account===a.id?null:a.id);onCapability?.('accounts')}}><span>{a.name}<small>•• {a.id} · {a.type==='credit'||a.type==='loan'?'Amount owed':'Available'}</small>{account===a.id&&<small>Demo account · USD<br/>Select Activity below to view transactions.</small>}</span><b>{money(a.balance)}</b></button>)}</>}
 {view==='/activity'&&member.transactions.map(t=><div className="account" key={t.id}><span>{t.name}<small>{t.date}</small></span><b>{money(t.amount)}</b></div>)}
 {view==='/cards'&&<div className="card-demo"><CreditCard size={28}/><h3>BECU Visa</h3><p>{member.firstName} · •• 6014</p><p>Illustrative card controls</p><CardControl/></div>}
 {view==='/move'&&<><p className="demo-note">Explore a transfer with sample data.</p><a className="app-cta" href="#money">Open transfer demo <ArrowUpRight size={15}/></a><div className="mini-fields">From <b>Everyday Checking</b>To <b>Choose a destination</b>Amount <b>$250.00</b></div></>}
 </div><nav className="app-nav" aria-label={`${member.firstName}'s demo navigation`}>{[[Home,'Home','/home'],[ArrowLeftRight,'Move','/move'],[List,'Activity','/activity'],[CreditCard,'Cards','/cards']].map(([Icon,label,path])=>{const I=Icon as typeof Home;return <button key={String(path)} disabled={mode==='display'} aria-label={String(label)} aria-pressed={view===path} onClick={()=>go(String(path))}><I size={19}/><small>{String(label)}</small></button>})}</nav></div>
}
function CardControl(){const [locked,setLocked]=useState(false);return <Button className="app-cta" aria-pressed={locked} onClick={()=>setLocked(!locked)}>{locked?'Unlock demo card':'Lock demo card'}</Button>}
export function FlutterExperience({src,route='/home',scenario='molly',startingState={},width=320,height=680,member=members[0],fallbackVideo,onCapability}:{src?:string;route?:string;scenario?:string;startingState?:Record<string,unknown>;width?:number;height?:number;member?:Member;fallbackVideo?:string;onCapability?:(id:string)=>void}){
 const [fallback,setFallback]=useState(false);const frame=useRef<HTMLIFrameElement>(null);
 const url=src?`${src}${src.includes('?')?'&':'?'}route=${encodeURIComponent(route)}&scenario=${encodeURIComponent(scenario)}`:undefined;
 const sendState=()=>{if(src&&frame.current){try{frame.current.contentWindow?.postMessage({type:'becu-experience:init',route,scenario,startingState},new URL(src,window.location.href).origin)}catch{setFallback(true)}}};
 useEffect(()=>{sendState()},[src,route,scenario,startingState]);
 return <div className="flutter-experience" style={{maxWidth:width}}><div className="product-label"><span className="status-dot"/>{src&&!fallback?'LIVE FLUTTER EXPERIENCE':'INTERACTIVE EXPERIENCE DEMO'}</div>{url&&!fallback?<><iframe ref={frame} src={url} title={`BECU Flutter experience: ${scenario}`} width={width} height={height} onLoad={sendState} onError={()=>setFallback(true)} allow="fullscreen"/><button className="text-button" onClick={()=>setFallback(true)}>App unavailable? View demo</button></>:fallbackVideo?<video controls playsInline src={fallbackVideo}/>:<BankingApp member={member} route={route} onCapability={onCapability}/>}<p className="product-disclosure">{src&&!fallback?'Connected application embed.':'Sample data · React demo · Flutter build pending'}</p></div>
}
export function JourneyPhone({step}:{step:number}){return step===4?<BankingApp mode="display"/>:<div className="phone onboarding-phone"><div className="island"/><div className="phone-top">9:41 <span>••• ▰</span></div><div className="app-brand"><BecuLogo/></div><div className="onboarding-content" key={step}><span className="step-symbol">{journey[step].icon}</span><small>YOUR BECU JOURNEY</small><h3>{journey[step].screen}</h3><p>{journey[step].detail}</p><div className="onboarding-status"><Check size={17}/>{journey[step].action}</div><div className="step-dots">{journey.map((_,i)=><i key={i} className={i<=step?'active':''}/>)}</div></div><p className="demo-note">Illustrative onboarding journey</p></div>}

